### ISSUE TITLE
Bugg when trying to use the THEN card

### ISSUE THREAD

**Issue by JohanBendz** [fredrikjohnsson/temperaturnu#7]
When trying to use the THEN card, inserting a hash from Temperature.nu and a temperature token from a local sensor the app crash with this message:

Hi!

Unfortunately, the app crashed while I was doing the following:

(...)

This is the stack trace:(node:25691) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at /drivers/temperature/device.js:81:39
    at Parser.<anonymous> (/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31)
(node:25691) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25691) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/app.js:37
				this.log('[reportTemperatureAction] Result is: ' + result);
				                                                   ^

ReferenceError: result is not defined
    at reportTemperatureAction.register.registerRunListener (/app.js:37:56)
    at FlowCardAction._onRun (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/FlowCard.js:1:1235)
    at emitThree (events.js:136:13)
    at FlowCardAction.emit (events.js:217:7)
    at ManagerFlow._onRun (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/flow.js:1:2267)
    at _eventListeners.filter.forEach.t (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1220)
    at Array.forEach (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1197)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)

**Comment by fredrikjohnsson** [comment]
This issue is resolved in the current beta (v1.1.1) that should be available shortly.
